version: '3'
services:
  web:
    build: .
    command: rails s -b 0.0.0.0
    container_name: bugle_app
    ports:
      - 3000:3000
    volumes:
      - .:/bugle_app
    depends_on:
      - db
    env_file:
      - .env.docker
    tty: true
    stdin_open: true
  db:
    image: postgres:14.1
    env_file:
      .env.docker
    volumes:
      - bugle_app_data:/var/lib/postgresql/data
volumes:
  bugle_app_data:
