default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>
  username: <%= ENV.fetch('POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_PASSWORD') %>
  host: <%= ENV.fetch('POSTGRES_HOST') %>

development:
  <<: *default
  database: bugle_app_development

test:
  <<: *default
  database: bugle_app_test

production:
  <<: *default
  database: bugle_app_production
  username: bugle_app
  password: <%= ENV['BUGLE_APP_DATABASE_PASSWORD'] %>
